sim:
	xrun topmultb.sv \
	../rtl/ps.sv  \
	../rtl/serialmuladd.sv  \
	../rtl/sp.sv \
	../rtl/topmul.sv \
	-access +rwc \
	-top topmultb

clean:
	rm -rf trace.vcd  xcelium.d  xrun.history  xrun.log xrun.key *~
